### ISSUE TITLE
Singleton Class Members

### ISSUE THREAD

**Issue by wentaoyuan** [lucidrains/byol-pytorch#5]
Forgive me for my unfamiliarity with software design, but I'm wondering why it is necessary to write a singleton wrapper for `projector` and `target_encoder`. Is there any disadvantage of initializing them in `__init__`?

**Comment by lucidrains** [comment]
@wentaoyuan Hello! The reason is because at initialization, we don't really know the dimensions of the representation emitted by the designated hidden layer (to be fed into the projection network).

I decide to lazy instantiate it to save users from having to run a torch summary and specify it manually.

**Comment by wentaoyuan** [comment]
That's brilliant. Thanks!

**Comment by lucidrains** [comment]
Glad you like it! Go make some neural nets smarter :)
